spring:
  datasource:
    url: jdbc:h2:mem:apprentice_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    # Access console: http://localhost:8080/h2-console
    console:
      enabled: true


app:
  # Possibilities: MAP, ARRAY, DATABASE
  storageType: 'DATABASE'